[theme]
base="dark"
primaryColor="#002342"        # Azul Duoc (Color principal cambiado a Azul)
backgroundColor="#212529"     # Gris Carb√≥n
secondaryBackgroundColor="#001529" # Azul Noche
textColor="#F8F9FA"           # Blanco
font="sans serif"